name: 'Hello World'
description: 'Greet someone and record the time'

inputs:
  spider-path:
    description: 'Full path to the spider'
    required: true
outputs:
  time:
    description: 'The time we greeted you'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.spider-path }}
